return {
    -- "amitds1997/remote-nvim.nvim",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim", -- For standard functions
    --     "MunifTanjim/nui.nvim", -- To build the plugin UI
    --     -- "nvim-telescope/telescope.nvim", -- For picking b/w different remote methods
    -- },
    -- config = true,
    -- opts = {
    --     progress_view = {
    --         type = "split",
    --     },
    --     offline_mode = {
    --         enabled = true,
    --         no_github = false,
    --     },
    --     remote = {
    --         copy_dirs = {
    --             compression = {
    --                 enabled = true,
    --             },
    --         },
    --     },
    -- },
}
